#!/usr/bin/env python
#!bin/bash

#Este script es necesario para que funcione #cc-genpro1.2
#Descargando paquetes
apt update && apt upgrade -y

pkg install python2
pkg install w3m
pkg install neofetch

from urllib2 import *
from platform import system
import sys
import json
dz = raw_input('\033[92mINGRESA TU BIN: \033[93m')
whois = "https://lookup.binlist.net/" + dz
dev = urlopen(whois).read()
print dev
